### ISSUE TITLE
In traing file occurs some error

### ISSUE THREAD

**Issue by eddie000000** [CanPeng123/Faster-ILOD#4]
here is my environment. I run it on colab.
torch                         1.1.0 
torchvision                   0.3.0  
I run this code 
python /content/drive/MyDrive/FA/Faster-ILOD/tools/train_first_step.py  --config-file "/content/drive/MyDrive/FA/Faster-ILOD/configs/e2e_faster_rcnn_R_50_C4_1x.yaml" 
then I met this problem 
[
![23](https://user-images.githubusercontent.com/43995973/129167646-ed61f07b-5f28-4cfd-87b0-70cb0b632d33.png)
](URL)

hope you can help me.
Thanks.

**Comment by eddie000000** [comment]
NUM_CLASSES
    NAME_OLD_CLASSES
    NAME_NEW_CLASSES
    NAME_EXCLUDED_CLASSES

I have already modified these files

**Comment by CanPeng123** [comment]
Hi, 

I remember last time some people also met this problem and it seems like it is due to the environment version. 
Could you please change the loss_dict to loss_dict[0] and try?
Hope this could help you.

Warm Regards
Can

**Comment by eddie000000** [comment]
> Hi,
> 
> I remember last time some people also met this problem and it seems like it is due to the environment version.
> Could you please change the loss_dict to loss_dict[0] and try?
> Hope this could help you.
> 
> Warm Regards
> Can

Thanks a lot.
It works.

**Comment by eddie000000** [comment]
@CanPeng123 
here is my e2e_faster_rcnn_R_50_C4_1x_Source_model.yaml
![image](https://user-images.githubusercontent.com/43995973/131449164-cd03d7d4-8bec-446d-a1c5-59147e232506.png)

and here is my e2e_faster_rcnn_R_50_C4_1x_Target_model.yaml
![image](https://user-images.githubusercontent.com/43995973/131449253-e543d9ce-0802-4ed0-ba7c-9cb199450801.png)

First, I trained 15 classes. I want to train 15+1+1+1+1+1 classes.
But I got this result in an incremental step. I add a new class (pottedplant).
![image](https://user-images.githubusercontent.com/43995973/131449399-1909bf17-24d2-40ea-b6db-bc7ff2f10355.png)

could you explain how to solve this problem?

**Comment by eddie000000** [comment]
After running Faster-ILOD/tools/train_first_step.py
There are only these files in the dir
![image](https://user-images.githubusercontent.com/43995973/131450612-9df07b45-5e5e-41d9-9469-544bffe3029f.png)

Therefore, I change the weight in e2e_faster_rcnn_R_50_C4_1x_Target_model.yaml
![image](https://user-images.githubusercontent.com/43995973/131450442-6c2c3faf-5e04-4105-9b59-acc4afb36f79.png)

**Comment by CanPeng123** [comment]
Hi,

Have you removed the optimization and iteration information in the pth file for the pre-trained model? 
Except for the model parameters, information about optimizer and iteration are all stored on the pth file. 
If you directly load the target model with the previously trained source model pth, the iteration information on it will be load to the target model. 
Then, the target model will not be trained since the required iteration steps have been matched.

**Comment by eddie000000** [comment]
> Hi,
> 
> Have you removed the optimization and iteration information in the pth file for the pre-trained model?
> Except for the model parameters, information about optimizer and iteration are all stored on the pth file.
> If you directly load the target model with the previously trained source model pth, the iteration information on it will be load to the target model.
> Then, the target model will not be trained since the required iteration steps have been matched.

After I ran the train_first_step.py and I only get model_final.pth 
I did not remove any files in the RPN_15_classes_40k_steps folder.

I can't find any pth file named model_trim_optimizer_iteration.pth

**Comment by CanPeng123** [comment]
Hi,

You need to remove the information about optimizer and iteration on the model_final.pth before loading it to the target model. 
Please take a look at the trim_detectron_model.py file.

**Comment by eddie000000** [comment]
thanks for your help. I'll give it a try.

**Comment by YuQianzi** [comment]
@CanPeng123 Could you please give a complete training step like: https://github.com/JosephKJ/iOD/blob/main/run.sh#L1-L8.

**Comment by YuQianzi** [comment]
@CanPeng123 I still feel confused about how to train the model after I execute  python tools/train_first_step.py --config-file ./configs/e2e_faster_rcnn_R_50_C4_1x.yaml
